version: 2

models:
  - name: dim_listings_cleansed
    description: "Cleansed dimension table for Airbnb listings"
    columns:
      - name: listing_id
        description: "Unique identifier for each listing"
        tests:
          - not_null
          - unique
      - name: host_id
        description: "Unique identifier for the host of the listing"
        tests:
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id
      - name: room_type
        description: "Type of room offered in the listing (e.g., entire home/apt, private room, shared room)"
        tests:
          - accepted_values:
              values: [ "Entire home/apt", "Private room", "Shared room", "Hotel room" ]
      - name: minimum_nights
        description: "{{ doc ('dim_listing_cleansed__minimum_nights') }}"
        tests:
          - positive_value
  - name: dim_hosts_cleansed
    description: "Cleansed dimension table for Airbnb hosts"
    columns:
      - name: host_id
        description: "Unique identifier for each host"
        tests:
          - not_null
          - unique
      - name: host_name
        description: "Name of the host"
        tests:
          - not_null
      - name: is_superhost
        description: "Indicates if the host is a superhost"
        tests:
          - accepted_values:
              values: [ "t", "f" ]
      - name: created_at
        description: "Date when the host joined Airbnb"
        tests:
          - not_null
      - name: updated_at
        description: "Date when the host information was last updated"
        tests:
          - not_null
  - name: dim_listing_with_hosts
    description: "Dimension table combining listings and their respective hosts"
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: "{{ source('airbnb', 'listings') }}"
    columns:
      - name: price
        tests:
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: 0.99
              min_value: 50 # (Optional)
              max_value: 500 # (Optional)
          - dbt_expectations.expect_column_max_to_be_between:
              max_value: 5000 # (Optional)
              config:
                severity: warn # (Optional)
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
  - name: base_airbnb_reviews
    description: The base_airbnb_reviews model processes raw Airbnb review data by selecting and renaming relevant columns, including listing ID, review date, reviewer name, comments, and sentiment. This model serves as a foundational dataset for further analysis and transformations.
    columns:
      - name: listing_id
        description: A unique identifier for the Airbnb listing associated with the review.
        data_type: number
      - name: date
        data_type: timestamp_ntz
      - name: reviewer_name
        data_type: varchar
      - name: comments
        data_type: varchar
      - name: sentiment
        data_type: varchar
