version: 2

sources:
  - name: airbnb
    database: AIRBNB
    schema: RAW
    tables:
      - name: listings
        identifier: RAW_LISTINGS
        columns:
          - name: room_type
            tests:
              - dbt_expectations.expect_column_distinct_count_to_equal:
                  value: 4
          - name: price
            tests:
              - dbt_expectations.expect_column_values_to_match_regex:
                  regex: "^\\\\$[0-9][0-9\\\\.]+$" 

      - name: hosts
        identifier: RAW_HOSTS

      - name: reviews
        identifier: RAW_REVIEWS
        loaded_at_field: date

        config:
          freshness:
            warn_after: { count: 1, period: hour }
            error_after: { count: 24, period: hour }
